# Generated by Django 5.0.1 on 2025-12-10 17:15

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(default="About Novyra Marketing", max_length=200),
                ),
                ("hero_subtitle", models.TextField(blank=True)),
                ("intro_text", ckeditor.fields.RichTextField()),
                (
                    "mission_title",
                    models.CharField(default="Our Mission", max_length=200),
                ),
                ("mission_text", ckeditor.fields.RichTextField()),
                (
                    "values_title",
                    models.CharField(default="Our Values", max_length=200),
                ),
                ("cta_title", models.CharField(blank=True, max_length=200)),
                ("cta_text", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "About Page Content",
                "verbose_name_plural": "About Page Content",
            },
        ),
        migrations.CreateModel(
            name="AboutValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-star",
                        help_text="Font Awesome icon class",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ContactPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_title", models.CharField(default="Contact Us", max_length=200)),
                ("hero_subtitle", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("business_hours", models.TextField(blank=True)),
                (
                    "form_title",
                    models.CharField(default="Send Us a Message", max_length=200),
                ),
            ],
            options={
                "verbose_name": "Contact Page Content",
                "verbose_name_plural": "Contact Page Content",
            },
        ),
        migrations.CreateModel(
            name="FloatingBackground",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/floating/"
                    ),
                ),
                (
                    "animation_speed",
                    models.CharField(
                        choices=[
                            ("slow", "Slow"),
                            ("medium", "Medium"),
                            ("fast", "Fast"),
                        ],
                        default="slow",
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("top-left", "Top Left"),
                            ("top-right", "Top Right"),
                            ("bottom-left", "Bottom Left"),
                            ("bottom-right", "Bottom Right"),
                            ("center", "Center"),
                        ],
                        default="center",
                        max_length=20,
                    ),
                ),
                ("opacity", models.FloatField(default=0.1, help_text="0.0 to 1.0")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HomePageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("services", "Services Section"),
                            ("stats", "Statistics Section"),
                            ("portfolio", "Portfolio Section"),
                            ("blog", "Blog Section"),
                            ("cta", "Call to Action"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("subtitle", models.TextField(blank=True)),
                ("content", ckeditor.fields.RichTextField(blank=True)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/backgrounds/"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#0006B1", help_text="Hex color code", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Homepage Section",
                "verbose_name_plural": "Homepage Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("hero_title", models.CharField(blank=True, max_length=200)),
                ("hero_subtitle", models.TextField(blank=True)),
                (
                    "hero_background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/services/"
                    ),
                ),
                ("intro_text", ckeditor.fields.RichTextField(blank=True)),
                ("main_content", ckeditor.fields.RichTextField()),
                ("features_title", models.CharField(blank=True, max_length=200)),
                ("process_title", models.CharField(blank=True, max_length=200)),
                ("cta_title", models.CharField(blank=True, max_length=200)),
                ("cta_text", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Service Page",
                "verbose_name_plural": "Service Pages",
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=100)),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-chart-line",
                        help_text="Font Awesome icon class",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-check-circle",
                        help_text="Font Awesome icon class",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="website.servicepage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
