# Generated by Django 5.0.1 on 2025-12-10 20:06

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Free Consultation", max_length=200),
                ),
                ("subtitle", models.TextField(blank=True)),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                (
                    "button_text",
                    models.CharField(default="Get Started", max_length=100),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/consultation/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Consultation Section",
                "verbose_name_plural": "Consultation Section",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", ckeditor.fields.RichTextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-star",
                        help_text="Font Awesome icon class",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/features/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FooterContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_text",
                    models.TextField(blank=True, help_text="About text in footer"),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="© 2025 Novyra Marketing LLC. All rights reserved.",
                        max_length=200,
                    ),
                ),
                ("newsletter_title", models.CharField(blank=True, max_length=200)),
                ("newsletter_text", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Footer Content",
                "verbose_name_plural": "Footer Content",
            },
        ),
        migrations.CreateModel(
            name="NavigationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "url",
                    models.CharField(
                        help_text="URL path or external URL", max_length=200
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_external",
                    models.BooleanField(
                        default=False, help_text="Check if external URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Link",
                "verbose_name_plural": "Navigation Links",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-check-circle",
                        help_text="Font Awesome icon class",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Process Step",
                "verbose_name_plural": "Process Steps",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="website/team/"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_position", models.CharField(blank=True, max_length=200)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("testimonial_text", models.TextField()),
                (
                    "client_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/testimonials/"
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(default=5, help_text="Rating out of 5"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero Section"),
                    ("features", "Features / Why Choose Us"),
                    ("services", "Services Section"),
                    ("process", "Process Section"),
                    ("stats", "Statistics Section"),
                    ("portfolio", "Portfolio Section"),
                    ("team", "Team Section"),
                    ("testimonials", "Testimonials Section"),
                    ("consultation", "Consultation Section"),
                    ("faq", "FAQ Section"),
                    ("blog", "Blog Section"),
                    ("contact", "Contact Section"),
                    ("cta", "Call to Action"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
