# Generated by Django 5.0.1 on 2025-12-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_contactmessage_videosection"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Basic Package, Premium Package, Elite Package",
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in Nigerian Naira (₦)",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="₦", help_text="Currency symbol", max_length=10
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        default="month",
                        help_text="e.g., month, year, one-time",
                        max_length=50,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list, help_text="List of features as strings"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Highlight this package"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pricing Package",
                "verbose_name_plural": "Pricing Packages",
                "ordering": ["order", "price"],
            },
        ),
        migrations.AlterField(
            model_name="videosection",
            name="video_url",
            field=models.URLField(
                help_text="YouTube or Vimeo URL (will be converted to embed format)"
            ),
        ),
    ]
