# Generated by Django 5.0.1 on 2025-12-10 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(default="Novyra Marketing", max_length=200),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Digital Marketing Agency", max_length=200
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        default="We help businesses grow through strategic digital marketing, compelling branding, and results-driven campaigns."
                    ),
                ),
                (
                    "admin_email",
                    models.EmailField(default="admin@novyra.com", max_length=254),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("login_attempts_limit", models.PositiveIntegerField(default=5)),
                (
                    "session_timeout",
                    models.PositiveIntegerField(
                        default=60, help_text="Session timeout in minutes"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
