# Generated by Django 5.0.1 on 2025-12-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="address_line_1",
            field=models.CharField(
                blank=True, default="Lagos, Nigeria", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="city",
            field=models.CharField(default="Lagos", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="country",
            field=models.CharField(default="Nigeria", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Favicon for browser tab",
                null=True,
                upload_to="site/favicon/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Main site logo",
                null=True,
                upload_to="site/logo/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="state",
            field=models.CharField(default="Lagos State", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="admin_email",
            field=models.EmailField(
                default="novyramarketingagency@gmail.com", max_length=254
            ),
        ),
    ]
