# Generated by Django 5.0.1 on 2025-12-10 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings_app", "0002_sitesettings_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="tiktok_url",
            field=models.URLField(
                blank=True, validators=[django.core.validators.URLValidator()]
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="x_handle",
            field=models.CharField(
                blank=True,
                help_text="X (Twitter) handle without @ (e.g., novyramarketing)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_url",
            field=models.URLField(
                blank=True, validators=[django.core.validators.URLValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="twitter_url",
            field=models.URLField(
                blank=True,
                help_text="X (formerly Twitter) URL",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
