# Generated by Django 5.0.1 on 2025-12-10 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings_app", "0003_sitesettings_tiktok_url_sitesettings_x_handle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_handle",
            field=models.CharField(
                blank=True,
                help_text="Facebook handle (e.g., novyramarketing)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram_handle",
            field=models.CharField(
                blank=True,
                help_text="Instagram handle (e.g., novyramarketing)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="linkedin_handle",
            field=models.CharField(
                blank=True,
                help_text="LinkedIn handle (e.g., company/novyramarketing)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tiktok_handle",
            field=models.CharField(
                blank=True,
                help_text="TikTok handle (e.g., novyramarketing)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_handle",
            field=models.CharField(
                blank=True,
                help_text="YouTube handle (e.g., @novyramarketing or channel ID)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="twitter_url",
            field=models.URLField(
                blank=True,
                help_text="Deprecated: Use x_handle instead",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
